security:
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: auto


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          anonymous: ~
          guard:
              authenticators:
                  - App\Security\LoginFormAuthenticator
                  - App\Security\OAuth\FacebookAuthenticator
              entry_point: App\Security\LoginFormAuthenticator
          remember_me:
              secret: '%kernel.secret%'
              lifetime: 604800 # 1 week in seconds
              path: /
              # by default, the feature is enabled by checking a
              # checkbox in the login form (see below), uncomment the
              # following line to always enable it.
              #always_remember_me: true
          logout:
              path: app_logout
              # where to redirect after logout
              # target: app_any_route

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_WORKER
            - ROLE_COMPANY
        ROLE_WORKER:
            -ROLE_USER
        ROLE_COMPANY:
            ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }