twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        max_jobs_on_homepage: '%max_jobs_on_homepage%'
        companies_web_directory: '%companies_web_directory%'
        locales: '%locales%'
